print("Output:\n")
print("Online Store")
print("---------------------------")
print("Product(S)                                Price")
print("Item 1                                    200.0")
print("Item 2                                    400.0")
print("Item 3                                    600.0")
print(f"Combo 1(Item 1 + 2)                       {(90*600)/100}")
print(f"Combo 2(Item 2 + 3)                       {(90*1000)/100}")
print(f"Combo 3(Item 1 + 3)                       {(90*800)/100}")
print(f"Combo 4(Item 1 + 2 + 3)                   {(75*1200)/100}\n")
print("---------------------------")
print("For delivery Contact:98764678899")                                                                                                        